# Generated by Django 4.1.6 on 2023-06-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0002_articles_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='create_ta',
        ),
        migrations.AddField(
            model_name='articles',
            name='create_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
